%% Declare RenderToolbox4 toolbox configuration.
%
% This script generates a JSON file which allows the ToolboxToolbox to
% automatically install RenderToolbox4.
%
% 2016 benjamin.heasly@gmail.com

config = [ ...
    tbToolboxRecord( ...
    'name', 'mitsuba-spectral-docker', ...
    'type', 'docker', ...
    'url', 'ninjaben/mitsuba-spectral', ...
    'importance', 'optional'), ...
    tbToolboxRecord( ...
    'name', 'mMitsuba', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mMitsuba.git'), ...
    tbToolboxRecord( ...
    'name', 'pbrt-v2-spectral-docker', ...
    'type', 'docker', ...
    'url', 'ninjaben/pbrt-v2-spectral-docker', ...
    'importance', 'optional'), ...
    tbToolboxRecord( ...
    'name', 'mPbrt', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mPbrt.git'), ...
    tbToolboxRecord( ...
    'name', 'mexximp', ...
    'type', 'include', ...
    'url', 'https://raw.githubusercontent.com/RenderToolbox3/mexximp/master/mexximpToolboxConfig.json'), ...
    tbToolboxRecord( ...
    'name', 'SphereRendererToolbox', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/SphereRendererToolbox.git', ...
    'importance', 'optional'), ...
    tbToolboxRecord( ...
    'name', 'Psychtoolbox-3', ...
    'type', 'git', ...
    'url', 'https://github.com/Psychtoolbox-3/Psychtoolbox-3.git', ...
    'subfolder', 'Psychtoolbox'), ...
    tbToolboxRecord( ...
    'name', 'RenderToolbox4_binary', ...
    'type', 'webget', ...
    'url', 'https://github.com/RenderToolbox3/RenderToolbox4/releases/download/v4.0/build.zip', ...
    'hook', 'clear mex'), ...
    tbToolboxRecord( ...
    'name', 'RenderToolbox4', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/RenderToolbox4.git', ...
    'localHookTemplate', 'rtbLocalConfigTemplate.m'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configFile = fullfile(pathHere, 'rtbToolboxConfig.json');
tbWriteConfig(config, 'configPath', configFile);

