%%% RenderToolbox4 Copyright (c) 2012-2013 The RenderToolbox4 Team.
%%% About Us://github.com/DavidBrainard/RenderToolbox4/wiki/About-Us
%%% RenderToolbox4 is released under the MIT License.  See LICENSE.txt.
%
% Generate scene files for all example scenes, but don't render them.
%
% This script is intended as an example for rendering in a production
% setting, like a computer cluster.  It's not intened as a general-purpose
% demo.
%
% GenerateAllExampleSceneFiles.m and RenderAllExampleSceneFiles.m work as a
% pair.  You should run GenerateAllExampleSceneFiles.m first, then run
% RenderAllExampleSceneFiles.m.
%
% This script is useful for generating lots and lots of scene files, to be
% rendererd later with RenderAllExampleScenes.  In some production
% settings, like computer clusters, it's useful to have a top-level script
% that takes no arguments, like this one.  You should copy this script and
% edit variables to agree with your system.
%
% For Mitsuba scene files, this script must be run from a machine that has
% OpenGL support.  This might not be the case for computer cluster worker
% nodes.
%
% See
% https://github.com/DavidBrainard/RenderToolbox4/wiki/Generate-and-RenderAllExampleSceneFiles.
%

%% Choose global RenderToolbox4 behavior.
setpref('RenderToolbox4', 'isParallel', false);
setpref('RenderToolbox4', 'isReuseSceneFiles', false);

%% Invoke execcutive scripts.
% choose where to put output files
%   for example '/Users/myName/epic-scene-test'
%   or empty '' for default folders (see rtbDefaultHints())
outputRoot = '';
makeFunctions = { ...
    'rtbMakeCheckerboard.m', ...
    'rtbMakeCheckerShadowScene', ...
    'MakeCoordinatesTest.m', ...
    'rtbMakeCubanSphere.m', ...
    'rtbMakeCubanSphereTextured.m', ...
    'rtbMakeDice.m', ...
    'MakeDragon.m', ...
    'rtbMakeDragonColorChecker.m', ...
    'rtbMakeDragonGraded.m', ...
    'rtbMakeDragonMaterials.m', ...
    'rtbMakeInterior.m', ...
    'rtbMakeInteriorDragon.m', ...
    'rtbMakeInterreflection.m', ...
    'rtbMakeMaterialSphere.m', ...
    'MakeMaterialSphereBumps.m', ...
    'rtbMakeMaterialSpherePortable.m', ...
    'MakeMaterialSphereRemodeled.m', ...
    'rtbMakeRadianceTestPBRT.m', ...
    'rtbMakeRadianceTestMitsuba.m', ...
    'rtbMakeScalingTest.m', ...
    'rtbMakeSimpleSphere.m', ...
    'rtbMakeSimpleSquare.m', ...
    'rtbMakeSpectralIllusion.m', ...
    'rtbMakeTableSphere.m'};
results = rtbTestAllExampleScenes(outputRoot, makeFunctions);
